### PR TITLE
Feat/Camunda Self-Managed - add oauth from Quarkus 3.x

### PR DESCRIPTION
**Pull request by forszpanen**
In our project we still use Quarkus 2.x but migration to Quarkus 3.x is ongoing. I've checked and also wrote in a previous issue that support for oauth would be needed for Quarkus2.x as well. I created a PR base on Quarkus3.x main branch. I adjusted adoc and added a little logger. I checked it with deployed instance of Camunda Self-Managed version 8.4.3 with Multi-Tenancy turned off and it works. For Multi-tenancy turned on I got 
"Expected to handle gRPC request CreateProcessInstance with tenant identifier '', but no tenant identifier was provided"
https://forum.camunda.io/t/how-to-start-a-process-instance-in-a-self-managed-multi-tenant-deployment-v8-3-3/49229
Diagrams were created in camunda-modeler 5.13.0 and Camunda version 8.2.12
Is is there any example how to write tests with oauth turned on? I couldn't find any and it seems devservice starts only zeebe engine without auth enabled. Am I right? @andrejpetras

### CODE REVIEW

**Comment by andrejpetras** [comment]
@forszpanen thank you for your PR.

Please note that version 0.x (Quarkus 2) is no longer supported as there is no supported Quarkus 2 version.
https://endoflife.date/quarkus-framework

* Multi-Tenancy: Zeebe tenant is not yet supported by the Quarkus Zeebe extension. Will be in next release
* OAuth test: zeebe devservice uses the default “Zeebe TestContainer” https://github.com/camunda-community-hub/zeebe-test-container, which does not have OAuth functionality

**Comment by forszpanen** [comment]
@andrejpetras thank you for your response is very helpful to understand how it works internally and what will be improved.
Please tell me, are you going to merge my PR or should I just merge it to my forked repo? I know that Quarkus3.x is now a main line but adding some missing feats to older version Quarkus2.x also might be helpful.

**Comment by andrejpetras** [comment]
@forszpanen I have to reject your PR

**Comment by forszpanen** [comment]
@andrejpetras I'm asking because we're going to add a PR for zeebe.client.enabled but should we create PR only for Quarkus3.x?
You closed my PR for Quarkus2.x so I understand that we have to host our forked version of quarkus-zeebe and if we'd like to add sth to Quarkus2.x, we need to add it **only** there? Correct?

**Comment by andrejpetras** [comment]
@forszpanen Any PR for Quarkus3.x is welcome.
Quarkus2.x is deprecated and no longer supported.

**Pull request closed without merging**
